services:
  - type: web
    name: hutta-home-services
    env: node
    buildCommand: yarn install
    startCommand: node backend/server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false